LocalLibrary/LocalLibrary/urls.py
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/catalog/')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

] 

LocalLibrary/catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index , name = 'index'),
    path('books/', views.BookListView.as_view() , name = 'books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'), 
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name = 'my-borrowed'),
    path('borrowed/', views.BorrowedBooksListView.as_view(), name = 'borrowed-books'),
    path('books/<int:pk>', views.book_detail_view, name = 'book-detail'),
    path('authors/', views.AuthorListView.as_view() , name = 'authors'),
    path('authors/<int:pk>', views.author_detail_view , name = 'author-detail'), 
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

LocalLibrary/catalog/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.forms import ModelForm

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")
    
    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])
    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
    def __str__(self):
        return '{0} ({1})'.format(self.id,self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False    

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ["last_name","first_name"]
    
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    def __str__(self):
        return '{0}, {1}'.format(self.last_name,self.first_name)
        
class Language(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name

"""An example of using ModelForm to create forms 

class RenewBookModelForm(ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back',]
        labels = { 'due_back': 'Renewal date',}
        help_texts = { 'due_back': 'Enter a date between now and 4 weeks (default 3).', } 

    def clean_due_back(self):
       data = self.cleaned_data['due_back']
       
       #Check date is not in past.
       if data < datetime.date.today():
           raise ValidationError('Invalid date - renewal in past')

       #Check date is in range librarian allowed to change (+4 weeks)
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError('Invalid date - renewal more than 4 weeks ahead')

       # Remember to always return the cleaned data.
       return data

 """    

LocalLibrary/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

import datetime #for checking renewal date range.


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = "Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        if data < datetime.date.today():
            raise ValidationError('Invalid date - renewal in past')
        if data > (datetime.date.today() + datetime.timedelta(weeks=4)):
            raise ValidationError('Invalid date - renewal more than 4 weeks ahead')
        return data
        

LocalLibrary/catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin , PermissionRequiredMixin
from .forms import RenewBookForm
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.



def index(request):
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()

    """Managing user sessions"""
    num_authors=Author.objects.count()
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    

    return render(
        request,
        'catalog/index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors ,'num_authors':num_authors,'num_visits':num_visits},
    )

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5
    context_name ='author_list'
    tempelate_name = 'author_list.html'
    
    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        return context
class BookListView(generic.ListView):
    model = Book
    paginate_by = 5
    context_object_name = 'book_list'
    template_name = 'book_list.html'
    
    def get_context_data(self , **kwargs):
        context = super(BookListView , self).get_context_data(**kwargs)
        return context

class LoanedBooksByUserListView(generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = BookInstance
    context_object_name = 'bookinstance_list'
    template_name = 'catalog/user_borrowed_books.html'
    paginate_by = 5
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
class BorrowedBooksListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    paginate_by = 5
    model = BookInstance
    template_name = 'catalog/borrowed_books_list.html'
    context_object_name = 'borrowed_books'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact = 'o').order_by('due_back')

    
def book_detail_view(request , pk):
    book_id = Book.objects.get(pk = pk)
    return render(
        request,
        'catalog/book_detail.html',
        context ={'book': book_id}           
    )

def author_detail_view(request , pk):
     author_id = Author.objects.get(pk= pk)
     books_by_author = Book.objects.filter(author = author_id)
     return render(
         request,
         'catalog/author_detail.html',
         context ={'author': author_id, 'books_by_author':books_by_author,}
     )


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request , pk):
    book_inst=get_object_or_404(BookInstance, pk = pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            return HttpResponseRedirect(reverse('borrowed-books') )
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})


class AuthorCreate(PermissionRequiredMixin,CreateView):
    model = Author
    fields = '__all__'
    initial={'date_of_death':'05/01/2018',}
    permission_required = 'catalog.can_mark_returned'
class AuthorUpdate(PermissionRequiredMixin,UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    permission_required = 'catalog.can_mark_returned'
class AuthorDelete(PermissionRequiredMixin,DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_mark_returned'

class BookCreate(PermissionRequiredMixin,CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
class BookUpdate(PermissionRequiredMixin,UpdateView):
    model = Book
    fields ='__all__'
    permission_required = 'catalog.can_mark_returned'
class BookDelete(PermissionRequiredMixin,DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.can_mark_returned'

LocalLibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

LocalLibrary/catalog/templates/catalog/author_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h2><strong>Author: </strong>{{author}}</h2>
    

    <div  style ="margin-left: 20px; margin-top:20px;">
        {% if author.date_of_birth %}
            <p>Date of birth: {{author.date_of_birth}} </p>
        {% endif %}
        {% if author.date_of_death %}
            <p>Date of death: {{author.date_of_death}} </p>
        {% endif %}
        <h2>Books</h2>
        {% for copy in books_by_author %}
            <p><strong><a href ="{%url 'book-detail' copy.id%}">{{copy}}</strong></a></p>
            <p>{{copy.summary}}</p>
        {% endfor %}
    </div>
{% endblock %}

LocalLibrary/catalog/templates/catalog/author_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

LocalLibrary/catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{%block content %}
    <h1>Author list</h1>
    {%if author_list %}
    <ul>
        {%for author in author_list %}
            <li>
                <a href ="{{author.get_absolute_url}}">{{author}} ({{author.date_of_birth}} - {{author.date_of_death}})</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No author has been registered yet</p>
    {% endif %}
{% endblock%}

LocalLibrary/catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->

  {% load static %}
  <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'books' %}">All books</a></li>
            <li><a href="{% url 'authors' %}">All authors</a></li> <br/>
            
        {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
        {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
        {% endif %} 
        </ul>
        {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% block content %} {% endblock %}
        {% block pagination %}
          {% if is_paginated %}
             
              <div class="pagination">
                  <span class="page-links">
                      {% if page_obj.has_previous %}
                          <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                      {% endif %}
                      <span class="page-current">
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                      </span>
                      {% if page_obj.has_next %}
                          <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                      {% endif %}
                  </span>
              </div>
          {% endif %}
        {% endblock %} 
      </div>
    </div>
  </div>
</body>
</html>

LocalLibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "catalog/base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete this book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

LocalLibrary/catalog/templates/catalog/book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Title: {{book.title}}</h1>
    <p><strong>Author: </strong><a href = "{%url 'author-detail' book.author.id %}"> {{book.author}}</a></p>
    <p><strong>Summary: </strong> {{book.summary}}</p>
    <p><strong>ISBN: </strong>{{book.isbn}}</p>
    <p><strong>Language: </strong>{{book.language}}</p>
    <p><strong>Genre: </strong>{% for genre in book.genre.all %} {{genre}}{% if not forloop.last %}, {%endif %} {% endfor %}</p>

    <div  style ="margin-left: 20px; margin-top:20px;" >
        <h4>Copies</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <!--<p class = "text-success" >{{copy.get_status_display}}</p>-->
            <p class = "{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
            {% if copy.status == 'a' %}
                <p><strong>Due to be returned :</strong>{{copy.due_back}}</p>
            {% endif %}
            <p><strong>Imprint :</strong>{{copy.imprint}}</p>
            <p class = "text-muted"><strong>Id:</strong>{{copy.id}}</p>
        {% endfor %}
    </div>

{% endblock %}

LocalLibrary/catalog/templates/catalog/book_form.html
{% extends "catalog/base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

LocalLibrary/catalog/templates/catalog/book_list.html
{% extends "catalog/base_generic.html" %}

{%block content %}
    <h1>Book list</h1>
    {%if book_list %}
    <ul>
        {%for book in book_list %}
            <li>
                <a href ="{{book.get_absolute_url}}">{{book.title}}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library</p>
    {% endif %}
{% endblock%}

LocalLibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}
{% block content %}
    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p {% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form}}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

LocalLibrary/catalog/templates/catalog/borrowed_books_list.html
{% extends "catalog/base_generic.html" %}
{% block content %}
    <h1>All Borrowed Books</h1>
    <ul>
        {% for borrowed_inst  in  borrowed_books%}
            <li class ="{% if borrowed_inst.is_overdue %} text-danger {% endif %}"><a>{{borrowed_inst.book.title}} {{borrowed_inst.id}} </a>
                ({{borrowed_inst.due_back}}) - {{borrowed_inst.borrower}} {% if perms.catalog.can_mark_returned %} -  <a href="{% url 'renew-book-librarian' borrowed_inst.id %}">Renew</a>{% endif %}</li>
        {% endfor %}
    </ul>       
{% endblock %}

LocalLibrary/catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Local Library Home</h1>
        <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>
    <h2>Dynamic content </h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong>{{num_books}}</li>
        <li><strong>Copies:</strong>{{num_instances}}</li>
        <li><strong>Copies available:</strong>{{num_instances_availabele}}</li>
        <li><strong>Authors:</strong>{{num_authors}}</li>
    </ul>

    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}

LocalLibrary/catalog/templates/catalog/user_borrowed_books.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>
    {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}